export const CategoryImages = {
  beauty: "/categories/beauty.webp",
  fragrances: "/categories/fragrances.webp",
  furniture: "/categories/furniture.webp",
  groceries: "/categories/groceries.webp",
  "home-decoration": "/categories/home-decoration.webp",
  "kitchen-accessories": "/categories/kitchen-accessories.webp",
  laptops: "/categories/laptops.webp",
  "mens-shirts": "/categories/mens-shirts.webp",
  "mens-shoes": "/categories/mens-shoes.webp",
  "mens-watches": "/categories/mens-watches.webp",
  "mobile-accessories": "/categories/mobile-accessories.webp",
  motorcycle: "/categories/motorcycle.webp",
  "skin-care": "/categories/skin-care.webp",
  smartphones: "/categories/smartphones.webp",
  "sports-accessories": "/categories/sports-accessories.webp",
  sunglasses: "/categories/sunglasses.webp",
  tablets: "/categories/tablets.webp",
  tops: "/categories/tops.webp",
  vehicle: "/categories/vehicle.webp",
  "womens-bags": "/categories/womens-bags.webp",
  "womens-dresses": "/categories/womens-dresses.webp",
  "womens-jewellery": "/categories/womens-jewellery.webp",
  "womens-shoes": "/categories/womens-shoes.webp",
  "womens-watches": "/categories/womens-watches.webp",
};
